name: ballet_for_all_flutter
description: Flutter app for 모두의 발레
publish_to: 'none'

version: 0.0.7+7

environment:
  sdk: '^3.0.5'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.8.0
  firebase_analytics: ^10.1.6
  flutter_svg: ^2.0.4
  equatable: ^2.0.5
  cloud_firestore: ^4.5.1
  json_annotation: ^4.8.0
  carousel_slider: ^4.2.1
  dots_indicator: ^3.0.0
  intl: ^0.18.1
  google_fonts: ^4.0.4
  get: ^4.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  json_serializable: ^6.6.1
  build_runner: ^2.3.3
  faker: ^2.1.0

flutter:
  uses-material-design: true
  assets:
  - assets/icons/
  - assets/images/
