// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfKak0_DkWJECUFwCNL9bO-nqZonFj_Zg',
    appId: '1:603456200455:web:3f8c0d225042da4a8a6fa2',
    messagingSenderId: '603456200455',
    projectId: 'ballet-for-all-project',
    authDomain: 'ballet-for-all-project.firebaseapp.com',
    storageBucket: 'ballet-for-all-project.appspot.com',
    measurementId: 'G-1QH8V802MX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmFFp3N7etsp8ot00mMUC_VnaT8YlGlZ8',
    appId: '1:603456200455:android:b2a54be8bec7987f8a6fa2',
    messagingSenderId: '603456200455',
    projectId: 'ballet-for-all-project',
    storageBucket: 'ballet-for-all-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQAyXtDMBHK196qplkEnRSBLTs9iuzgQo',
    appId: '1:603456200455:ios:ef4aaf4c8553882e8a6fa2',
    messagingSenderId: '603456200455',
    projectId: 'ballet-for-all-project',
    storageBucket: 'ballet-for-all-project.appspot.com',
    iosClientId: '603456200455-b9mfipbg5hvajusmfbbvlnmce8k85dsp.apps.googleusercontent.com',
    iosBundleId: 'com.wongeunjeon.balletforallapp',
  );
}
