// Mocks generated by Mockito 5.4.0 from annotations
// in ballet_for_all_flutter/test/repository/city/firestore_city_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:ballet_for_all_flutter/firebase/firestore_locations/firestore_locations_collection.dart'
    as _i2;
import 'package:cloud_firestore/cloud_firestore.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [FirestoreLocationsCollection].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirestoreLocationsCollection extends _i1.Mock
    implements _i2.FirestoreLocationsCollection {
  MockFirestoreLocationsCollection() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<Map<String, dynamic>> getLocation() => (super.noSuchMethod(
        Invocation.method(
          #getLocation,
          [],
        ),
        returnValue:
            _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i3.Future<Map<String, dynamic>>);
  @override
  Map<String, dynamic> docToMap(_i4.QueryDocumentSnapshot<Object?>? doc) =>
      (super.noSuchMethod(
        Invocation.method(
          #docToMap,
          [doc],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);
}
